### ISSUE TITLE
Dynamic import breaks Webpack.JS

### ISSUE THREAD

**Issue by baybal** [NordicSemiconductor/bluetooth-uuid-database#3]
Hello,

We have bad news for you: things like `require(pathForJson('company_ids'))` are breaking a popular module bundler called Webpack.JS

An easy way to work that around is to not to use them. A hard way is there too, and it involves doing a transpilator setup, and a few polyfills easily adding few megs of javascript to setup...

Webpack broke javascript ecosystem? Yes, but what we can do

**Comment by datenreisender** [comment]
AFAICS the code where dynamic requires are used is currently not intended to be used with a bundler like webpack. So I will close this issue.
